name: Wedding planner CI/CD

on:
  pull_request:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install PNPM Dependencies
        run: pnpm i

      - name: Lint Code
        run: pnpm lint

      - name: Type Check
        run: pnpm tsc --noEmit

      - name: Build PNPM Assets
        run: pnpm build
