name: Wedding planner CI/CD

on:
  push: # Trigger on push to any branch
    branches:
      - '**'
  pull_request: # Trigger on pull requests
    branches:
      - '**'

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install Node.js
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Step 3: Install PNPM
    - name: Install PNPM
      run: npm install -g pnpm

    # Step 4: Install Dependencies
    - name: Install PNPM Dependencies
      run: pnpm i

    # Step 5: Lint Code
    - name: Lint Code
      run: pnpm lint

    # Step 6: Run Tests
    - name: Run Tests
      run: pnpm test -- --coverage

    # Step 7: Type Checking
    - name: Type Check
      run: pnpm tsc --noEmit

    # Step 8: Build Storybook
    - name: Build Storybook
      run: pnpm storybook:build

    # Step 9: Build Next.js App
    - name: Build PNPM Assets
      run: pnpm build
