name: Wedding planner to prod

on: 
  push: 
    branches: 
          -main
jobs: 
  deploy:
    runs on: windows-latest

    steps:
    - name:  Checkout Code 
      uses:  actions/checkout@v3

    - name: Install Node.js
      uses: action/setup-node@v3
      with: 
        node-version: '20'

    - name: Install PNPM Dependencies
      run: pnpm i

    - name: Lint Code
      run: pnpm lint

    - name: Run Tests
      run: pnpm test -- --coverage

    - name: Type Check
      run: pnpm tsc --noEmit

    - name: Build PNPM Assets
      run: pnpm build

    
